name: Contoso
image: microsoftvisualstudio_windowsplustools_base-win11-gen2
hostInformation: general_i_8c32gb256ssd_v2
setupTasks:
  - task: winget
    inputs:
      package: Microsoft.VisualStudioCode
  - task: winget
    inputs:
      package: Microsoft.Azd
  - task: winget
    inputs:
      package: Microsoft.AzureCLI
  - task: winget
    inputs:
      package: Microsoft.PowerShell
  - task: powershell
    description: print information
    inputs:
      command: Write-Output "Running as $(whoami)"| Out-File C:\DeployAgent\test.log
